export const ImagesAssets = {
    partner: require('./handshake.png'),
    personal: require('./user.png'),
    angle: require('./angle.png'),
    removePartner: require('./dislike.png'),
    aboutUs: require('./info.png'),
    teddy: {
        A: require('./teddy/A.jpg'),
        B: require('./teddy/B.jpg'),
        C: require('./teddy/C.jpg'),
        D: require('./teddy/D.jpg'),
        E: require('./teddy/E.jpg'),
        F: require('./teddy/F.jpg'),
        G: require('./teddy/G.jpg'),
        H: require('./teddy/H.jpg'),
        I: require('./teddy/I.jpg'),
        J: require('./teddy/J.jpg'),
        K: require('./teddy/K.jpg'),
        L: require('./teddy/L.jpg'),
        M: require('./teddy/M.jpg'),
        N: require('./teddy/N.jpg'),
        O: require('./teddy/O.jpg'),
        P: require('./teddy/P.jpg'),
        Q: require('./teddy/Q.jpg'),
        R: require('./teddy/R.jpg'),
        // S: require('./teddy/S.jpg'),
        T: require('./teddy/T.jpg'),
        U: require('./teddy/U.jpg'),
        V: require('./teddy/V.jpg'),
        W: require('./teddy/W.jpg'),
        X: require('./teddy/X.jpg'),
        Y: require('./teddy/Y.jpg'),
        Z: require('./teddy/Z.jpg')
    }
}
